# Generated by Django 3.1.6 on 2021-08-18 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0008_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Requirement',
        ),
    ]
