# Generated by Django 3.1.6 on 2021-08-24 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0009_delete_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('surname', models.CharField(max_length=150, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(max_length=150)),
                ('start_date', models.DateField()),
                ('province', models.CharField(choices=[('Gauteng', 'Gauteng'), ('Mpumalanga', 'Mpumalanga'), ('KwaZulu Natal', 'KwaZulu Natal'), ('Free State', 'Free State'), ('Limpopo', 'Limpopo'), ('North West', 'North West'), ('Eastern Cape', 'Eastern Cape'), ('Western Cape', 'Western Cape'), ('Northern Cape', 'Northern Cape')], max_length=150, null=True)),
                ('industry', models.CharField(choices=[('Business Services', 'Business Services'), ('Information Technology', 'Information Technology'), ('Financial Services', 'Financial Services'), ('Public Sector', 'Public Sector'), ('Energy & Natural Resources', 'Energy & Natural Resources'), ('Industrial / Manufacturing', 'Industrial / Manufacturing'), ('Retail', 'Retail')], max_length=150, null=True)),
                ('social', models.CharField(choices=[('Facebook', 'Facebook'), ('LinkedIn', 'LinkedIn'), ('Twitter', 'Twtter'), ('Google+', 'Google+'), ('Email', 'Email'), ('Mindworx Website', 'Mindworx Website')], max_length=150, null=True)),
                ('job_title', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100)),
                ('videoupload', models.FileField(upload_to='videoupload/%y')),
            ],
        ),
    ]
