# Generated by Django 3.1.6 on 2021-08-24 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0011_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VideoUpload',
        ),
    ]
