# Generated by Django 3.1.6 on 2021-08-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruit', '0012_delete_videoupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CvTemplate',
        ),
    ]
